config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :tweets
  resources :likes, only: [:create, :destroy]
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy
    has_one :profile
    has_many :likes, dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet
    
    validates :password, presence: true, confirmation: true
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
        def current_user
            if session[:login_uid]
                User.find_by(uid: session[:login_uid])
            end
        end
        
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user) #もし～じゃなかったら
            tweet.like(current_user)
        end
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render "login"
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user != nil
      login_password = BCrypt::Password.new(user.pass)
      if login_password == params[:pass]
        session[:login_uid] = user.uid
        redirect_to root_path
      else
        render "login"
      end
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
        @tweet = Tweet.new
    end
    
    def create
        tweet_message = params[:message]
        tweet = current_user.tweets.new(message: tweet_message)
        if tweet.save
            puts "ツイート保存成功"
            redirect_to root_path
        else
            puts "ツイート保存失敗: #{tweet.errors.full_messages.join(", ")}"
            render "new"
        end
    end
    
    def destroy
        delete_tweet = Tweet.find(params[:id])
        delete_tweet.destroy
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(
        uid: params[:uid],
        password: params[:password],
        password_confirmation: params[:password_confirmation])
        if @user.save
            redirect_to users_path
        else
            render 'new'
        end
    end
    
    def destroy
        delete_user = User.find(params[:id])
        delete_user.destroy
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post, data: {turbo: false}  do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/tweets/index.html.erb
<% @tweets.each do |t| %>
    <p>
        <%= t.message %><%= link_to "削除", tweet_path(t), data: {turbo_method: :delete} %>
        <% if t.liked?(current_user) %>
            <%= link_to 'いいね削除', like_path(t), data: {turbo_method: :delete} %>
        <% else %>
            <%= link_to 'いいね', likes_path(tweet_id: t.id), data: {turbo_method: :post} %>
        <% end %>
    </p>
<% end %>

<% if current_user %>
  <%= form_tag '/tweets', {action: :create} do %>
    <%= hidden_field_tag :user_id, current_user.id %>
    <%= label_tag :message, 'メッセージ' %>
    <%= text_field_tag :message %>
    <%= submit_tag 'ツイート' %>
  <% end %>
<% end %>

<hr>
<% if current_user %>
    <p><%= link_to 'ログアウト', top_logout_path %></p>
<% else %>
    <p><%= link_to 'ログイン', top_main_path %></p>
<% end %>
<p>
    <%= link_to 'ユーザ一覧', users_path %>
</p>

app/views/tweets/new.html.erb
<%= form_tag tweets_path, method: :post, data: {turbo: false} do %>
    <%= hidden_field_tag :user_id, current_user.id %>
    <%= label_tag :message, 'メッセージ' %>
    <%= text_field_tag :message %>
    <%= submit_tag '新規登録' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |u| %>
    <p>
        <%= u.uid %><%= link_to "削除", user_path(u), data: {turbo_method: :delete} %>
    </p>
<% end %>


<p>
    <%= link_to "新規追加", new_user_path %>
</p>
<hr>
<%= link_to "ツイート一覧", tweets_path %>

app/views/users/new.html.erb
<%= form_tag users_path, method: :post, data: {turbo: false} do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :password, 'パスワード' %>
    <%= password_field_tag :password %>
    <%= label_tag :password_confirmation, 'パスワード(確認)' %>
    <%= password_field_tag :password_confirmation %>
    <%= submit_tag '新規登録' %>
<% end %>